<?php

namespace Fanta\Repository;

/**
 * Player
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Player extends \Doctrine\ORM\EntityRepository
{
}
